### ISSUE TITLE
Upgrading to Swagger 2.0.1 Not Working

### ISSUE THREAD

**Issue by kalexmills** [smoketurner/dropwizard-swagger#104]
Upgrading to Swagger 2.0.1 doesn't seem to be just a matter of excluding old dependencies and adding new ones, as I expected after looking through the README. Here is the relevant section of my pom.xml:

```
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-jaxrs2</artifactId>
            <version>2.0.1</version>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-core</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>1.3.0-1</version>
            <exclusions>
                <exclusion>
                    <groupId>io.swagger</groupId>
                    <artifactId>swagger-jersey2-jaxrs</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

On start up, I am receiving a NoClassDefinitionFoundError when initializing the bundle as explained in the Readme.

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/swagger/core/filter/SwaggerSpecFilter
	at com.flavorate.users.AuthenticationApp.initialize(AuthenticationApp.java:36)
	at io.dropwizard.Application.run(Application.java:88)
	at com.flavorate.users.AuthenticationApp.main(AuthenticationApp.java:32)
Caused by: java.lang.ClassNotFoundException: io.swagger.core.filter.SwaggerSpecFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
```

Here is the bundle init, the second line in this snippet is line 39 from above.

```
    public void initialize(Bootstrap<AuthenticationConfig> bootstrap) {
        bootstrap.addBundle(new SwaggerBundle<AuthenticationConfig>() {
            @Override
            protected SwaggerBundleConfiguration getSwaggerBundleConfiguration(AuthenticationConfig authenticationConfig) {
                return authenticationConfig.getSwaggerBundleConfiguration();
            }
        });
    }
```

Any clue about what I can do to upgrade to the new OpenAPI spec? This is greenfield development, so I'd like to depend on the most up-to-date libraries as much as possible.

I'm willing to attempt a PR if you have any ideas on what may need to be updated here. I know Swagger 2.X includes lots of breaking changes.

**Comment by kalexmills** [comment]
Also, it might just be me doing something stupid with my pom.xml...
