### ISSUE TITLE
Reflections ClassNotFoundException [Warning]

### ISSUE THREAD

**Issue by jadams74** [smoketurner/dropwizard-swagger#113]
we've a ton of warnings regarding org.reflections.Reflections not finding types. I've found threads in the dropwizard google group indicating exclusions of org.reflections.Reflections. This didn't work for me, it opened up a rabbit hole of mising types.

Any insight into how to resolve runtime warnings like this one:

```
WARN  [2018-10-30 20:53:31,027] org.reflections.Reflections: could not get type for name org.osgi.framework.BundleListener from any class loader
! java.lang.ClassNotFoundException: org.osgi.framework.BundleListener
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
```

**Comment by jadams74** [comment]
This turned out to be a transient dependency in our projects.  Closed.
