### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by inrix-adasgupta** [smoketurner/dropwizard-swagger#128]
Disclaimer: I'm new to swagger.

I've created a dropwizard web application. I'm trying to enable swagger for my APIs. 

When I try to access the URL http://[server]:[port]/swagger.json, I see following exception in log -

```
 [2019-04-16 22:47:00,760][ERROR][dw-18 - GET /swagger.json:18e584f4-77d1-4ef6-82b8-c643023cb39e][i.d.j.e.LoggingExceptionMapper]: Error handling a request: 3cb6dfa164a46b0f
 ! java.lang.NullPointerException: null
 ! at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:52)
 ! at io.swagger.jaxrs.listing.BaseApiListingResource.process(BaseApiListingResource.java:128)
 ! at io.swagger.jaxrs.listing.BaseApiListingResource.getListingJsonResponse(BaseApiListingResource.java:155)
 ! at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:32)
 ! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 ! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 ! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 ! at java.lang.reflect.Method.invoke(Method.java:498)
 ! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
 ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
 ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
 ! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
 ! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
 ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
 ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
 ! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
 ! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
 ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
 ! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
 ! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
 ! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
 ! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
 ! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
 ! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
 ! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
 ! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
 ! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
 ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
 ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
 ! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
 ! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
 ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
 ! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
 ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
 ! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
 ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 ! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
 ! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
 ! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
 ! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
 ! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
 ! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
 ! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
 ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
 ! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
 ! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
 ! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
 ! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
 ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 ! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
 ! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
 ! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
 ! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
 ! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
 ! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
 ! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
 ! at org.eclipse.jetty.server.Server.handle(Server.java:502)
 ! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
 ! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
 ! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
 ! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
 ! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
 ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
 ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
 ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
 ! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
 ! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
 ! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
 ! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
 ! at java.lang.Thread.run(Thread.java:748)
```

Following are my configurations -

pom.xml
```xml
 <dependencies>
     <dependency>
       <groupId>io.dropwizard</groupId>
       <artifactId>dropwizard-core</artifactId>
       <version>1.3.9</version>
     </dependency>
     <dependency>
       <groupId>com.google.inject</groupId>
       <artifactId>guice</artifactId>
       <version>4.2.2</version>
       <exclusions>
         <exclusion>
           <groupId>aopalliance</groupId>
           <artifactId>aopalliance</artifactId>
         </exclusion>
         <exclusion>
           <groupId>javax.inject</groupId>
           <artifactId>javax.inject</artifactId>
         </exclusion>
       </exclusions>
     </dependency>
     <dependency>
       <groupId>ru.vyarus</groupId>
       <artifactId>dropwizard-guicey</artifactId>
       <version>4.2.2</version>
     </dependency>
     <dependency>
       <groupId>com.smoketurner</groupId>
       <artifactId>dropwizard-swagger</artifactId>
       <version>1.3.9-1</version>
       <exclusions>
         <exclusion>
           <groupId>org.reflections</groupId>
           <artifactId>reflections</artifactId>
         </exclusion>
       </exclusions>
     </dependency>
     <dependency>
       <groupId>org.reflections</groupId>
       <artifactId>reflections</artifactId>
       <version>0.9.10</version>
       <exclusions>
         <exclusion>
           <groupId>com.google.code.findbugs</groupId>
           <artifactId>annotations</artifactId>
         </exclusion>
       </exclusions>
     </dependency>
...
  <build>
  ...
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <createDependencyReducedPom>false</createDependencyReducedPom>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <transformers>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                  <mainClass>com.blah.MyApplication</mainClass>
                </transformer>
              </transformers>
            </configuration>
          </execution>
        </executions>
      </plugin>
...
```

Unfortunate that documentation doesn't say anything about excluding reflections package. Had to find out through google search and scavenging through bug reports.

app.yaml
```
swagger:
  resourcePackage: com.bla.bla1, com.blah.bla2
  uriPrefix: /
```

Application initialization code
```java
 @Override
     public void initialize(Bootstrap<MyConfiguration> bootstrap) {
         ...
         bootstrap.addBundle(new SwaggerBundle<MyConfiguration>() {
             @Override
             protected SwaggerBundleConfiguration getSwaggerBundleConfiguration(MyConfiguration configuration) {
                 return configuration.getSwaggerBundleConfiguration();
             }
         });
         ...
     }
```

Annotations in resource class -
```java
 package com.bla.bla1;
 ...
 @Path("/consumer/crossing")
 public class CrossingResource {
 ...
 @POST
     @Consumes(MediaType.APPLICATION_JSON)
     @Produces(MediaType.APPLICATION_JSON)
     @Timed
     @ExceptionMetered
     @ApiOperation(value = "Get one or more crossings",
             response = BatchCrossingResponse.class)
     @ApiResponses(value = {
             @ApiResponse(code = 400, message = "")
     })
     public Response getCrossings(
             @ApiParam(value = "Batch crossing request", required = true) BatchCrossingRequest request) {
 ...
 }
```

What am I doing wrong?

**Comment by inrix-adasgupta** [comment]
This issue can be closed. NPE happened due to missing @Api annotation at class level.
