### ISSUE TITLE
Build error with versions 1.3.7 and up.

### ISSUE THREAD

**Issue by gintsgints** [smoketurner/dropwizard-swagger#149]
When I build dropwizard project using dropwizard-swagger 1.3.7 and up, I get build error.
As I read somewhere else, this is about guava conflicting versions:

```
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.toImmutableList()Ljava/util/stream/Collector;
	at org.jdbi.v3.guava.GuavaCollectors$Factory.<init>(GuavaCollectors.java:255)
	at org.jdbi.v3.guava.GuavaCollectors.factory(GuavaCollectors.java:84)
	at org.jdbi.v3.guava.GuavaPlugin.customizeJdbi(GuavaPlugin.java:26)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$consumer$0(Unchecked.java:35)
	at org.jdbi.v3.core.Jdbi.installPlugin(Jdbi.java:233)
	at io.dropwizard.jdbi3.JdbiFactory.configure(JdbiFactory.java:120)
	at io.dropwizard.jdbi3.JdbiFactory.build(JdbiFactory.java:88)
	at io.dropwizard.jdbi3.JdbiFactory.build(JdbiFactory.java:46)
	at com.balcia.binsy.ws.RestWSApp.run(MainApp.kt:43)
	at com.balcia.binsy.ws.RestWSApp.run(MainApp.kt:22)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.balcia.binsy.ws.RestWSApp$Companion.main(MainApp.kt:27)
	at com.balcia.binsy.ws.RestWSApp.main(MainApp.kt)
```

**Comment by gintsgints** [comment]
Ping?

**Comment by jplock** [comment]
That looks like an issue with jdbi
