### ISSUE TITLE
Compatibility issues with 'jackson-datatype-jsr310 version: '2.11.1

### ISSUE THREAD

**Issue by darewreck54** [smoketurner/dropwizard-swagger#196]
When I force an upgrade to 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310' to version 2.11.1, I get issue starting up dropwizard.  It happens in Application.java in dropwizard-core, when it tries to execute the command to execute the server with an json configuration.  

![image](https://user-images.githubusercontent.com/16171726/89149213-c6d0ff00-d510-11ea-85f9-f055e34ac86d.png)

It ends up throwing an exception:

```
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType(Lcom/fasterxml/jackson/databind/type/TypeBindings;)Lcom/fasterxml/jackson/databind/JavaType;
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:425)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:203)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:257)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:203)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:103)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:175)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:126)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:83)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:63)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:905)
	at io.swagger.jaxrs.Reader.read(Reader.java:326)
	at io.swagger.jaxrs.Reader.read(Reader.java:176)
	at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:252)
	at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:231)
	at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:318)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:80)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:46)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
``` 
This only happens when I try to use dropwizard-swagger: 

![image](https://user-images.githubusercontent.com/16171726/89149753-1237dd00-d512-11ea-9964-bc8cc5dce5c4.png)

I'm using  compile group: 'com.smoketurner', name: 'dropwizard-swagger', version: '2.0.0-1'

When I comment it out, it dropwizard works.

```
./gradlew dependencyInsight --dependency jackson-datatype-jsr310  

com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.5 -> 2.11.1
\--- io.dropwizard:dropwizard-jackson:2.0.12
     +--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2)
     |    +--- compileClasspath
     |    +--- com.smoketurner:dropwizard-swagger:2.0.0-1
     |    |    \--- compileClasspath
     |    +--- ru.vyarus:dropwizard-guicey:5.0.1
     |    |    \--- compileClasspath
     |    +--- io.dropwizard:dropwizard-auth:2.0.0
     |    |    \--- com.smoketurner:dropwizard-swagger:2.0.0-1 (*)
     |    +--- io.dropwizard:dropwizard-assets:2.0.0
     |    |    \--- com.smoketurner:dropwizard-swagger:2.0.0-1 (*)
     |    \--- io.dropwizard:dropwizard-views:2.0.0
     |         +--- com.smoketurner:dropwizard-swagger:2.0.0-1 (*)
     |         \--- io.dropwizard:dropwizard-views-freemarker:2.0.0
     |              \--- com.smoketurner:dropwizard-swagger:2.0.0-1 (*)
     +--- io.dropwizard:dropwizard-configuration:2.0.12
     |    \--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2) (*)
     +--- io.dropwizard:dropwizard-jersey:2.0.12
     |    \--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2) (*)
     +--- io.dropwizard:dropwizard-jetty:2.0.12
     |    \--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2) (*)
     +--- io.dropwizard:dropwizard-request-logging:2.0.12
     |    \--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2) (*)
     +--- io.dropwizard:dropwizard-logging:2.0.12
     |    +--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2) (*)
     |    +--- io.dropwizard:dropwizard-jersey:2.0.12 (*)
     |    +--- io.dropwizard:dropwizard-jetty:2.0.12 (*)
     |    \--- io.dropwizard:dropwizard-request-logging:2.0.12 (*)
     \--- io.dropwizard:dropwizard-metrics:2.0.12
          \--- io.dropwizard:dropwizard-core:2.0.12 (conflict resolution between versions 2.0.12, 2.0.0 and 2.0.2) (*)

```

Thanks,
Derek

**Comment by darewreck54** [comment]
@jplock is this repo still maintained?

**Comment by jplock** [comment]
Yes but I don’t actively use this project any longer. Happy to review and merge pull requests and add contributors.

**Comment by chrisrohr** [comment]
@darewreck54 I just looked locally and this library right now is on DW 2.0.10 which brings in jackson-datatype-jsr310 2.10.4.  When I bumped it to DW 2.0.12 it updated jackson-datatype-jsr310 to 2.10.5.

I see you are looking to use 2.11.1.  This will cause a dependency convergence, but since you said this is only a problem when you add dropwizard-swagger, it is probably an issue further down conflicting with swagger-core itself.

**Comment by kslats9** [comment]
I am also getting the NoSuchMethodError on getType. Has anyone found a solution or workaround?

**Comment by bmsq** [comment]
We just ran into this issue after upgrading Dropwizard (to v2.1.0).  As previous comments indicate, the root cause is that swagger v1.6.0 is not compatible with Jackson v2.11.1+.  To fix, dropwizard-swagger needs to upgrade swagger-jersey2-jaxrs from v1.6.0 to v1.6.2+.  

As a workaround, we are using the following Maven changes to force the use of swagger-jersey2-jaxrs v1.6.6 which resolves the issue for us while running Dropwizard 2.1.0:
```
        <dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>2.0.0-1</version>
            <exclusions>
            	<exclusion>
            		<groupId>io.swagger</groupId>
            		<artifactId>swagger-jersey2-jaxrs</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
        <dependency>
       		<groupId>io.swagger</groupId>
            <artifactId>swagger-jersey2-jaxrs</artifactId>
            <version>1.6.6</version>
        </dependency>
```
