### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by nipungoel2000** [smoketurner/dropwizard-swagger#274]
I am getting the following error when I integrate swagger-2.0.0-1 in my existing dropwizard application where the drowizard-core version used in 2.0.25. 
java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonProperty.namespace()Ljava/lang/String;
    at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.findNameForSerialization(JacksonAnnotationIntrospector.java:1080)
    at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForSerialization(AnnotationIntrospectorPair.java:605)
    at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForSerialization(AnnotationIntrospectorPair.java:602)
    at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.findNameForSerialization(AnnotationIntrospectorPair.java:605)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:561)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:421)
    at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:270)
    at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
    at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:391)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:224)
    at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173)
    at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
    at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463)
    at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
    at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
    at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4519)
    at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4498)
    at io.dropwizard.configuration.ConfigurationMetadata.<init>(ConfigurationMetadata.java:76)
    at io.dropwizard.configuration.BaseConfigurationFactory.<init>(BaseConfigurationFactory.java:76)
    at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:29)
    at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:18)
    at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:135)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
    at io.dropwizard.cli.Cli.run(Cli.java:78)
    at io.dropwizard.Application.run(Application.java:94)
    
    
    The application works fine if I comment out the swagger integration code part. Seems like some version issue to me but I am unable to figure out the exact problem.
    
    Please note that this is how I imported my swagger dependencies : 
    compile : 'io.swagger:swagger-jersey2-jaxrs:1.6.6'
    compile ('com.smoketurner:dropwizard-swagger:2.0.0-1'){
     exclude group: 'io.swagger', module: 'swagger-jersey2-jaxrs'
  }

**Comment by spadmanaban16** [comment]
Hello - am wondering when we will get a new release created. Last time it happened was in 2020 (https://mvnrepository.com/artifact/com.smoketurner/dropwizard-swagger), am interested in getting the latest swagger updates - https://github.com/smoketurner/dropwizard-swagger/commit/27010fd317a706b2b72853aebf68914fb6e26cd9.
