### ISSUE TITLE
Error while Running dropwizard-swagger

### ISSUE THREAD

**Issue by ashishrathore1** [smoketurner/dropwizard-swagger#53]
Hi I am getting following error while running my dropwizard-swagger Application. Unable to find the issue

INFO  [2016-09-19 03:29:02,103] io.dropwizard.assets.AssetsBundle: Registering AssetBundle with name: swagger-assets for path /swagger-static/*
Exception in thread "main" java.lang.NoSuchMethodError: org.reflections.util.ClasspathHelper.forPackage(Ljava/lang/String;[Ljava/lang/ClassLoader;)Ljava/util/Collection;
    at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:247)
    at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:221)
    at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:204)
    at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:252)
    at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:61)
    at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:32)
    at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
    at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:80)
    at com.lk.leadservice.DropdemowithhibernateApplication.main(DropdemowithhibernateApplication.java:66)

**Comment by jplock** [comment]
This package is compiled against jdk8.  Could you possibly be using jdk7 or have an older dependency version somewhere on the class path?

**Comment by DOSarrest** [comment]
We ran into this same problem. After examining the Dependency Hierarchy we discovered one of the other dependencies overrode the reflections package from 0.9.10 to 0.9.8 (from dropwizard-jobs-core).

Modifying the project pom.xml to include this resolved the conflict...

```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-bom</artifactId>
                <version>${dropwizard.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
            	<groupId>org.reflections</groupId>
            	<artifactId>reflections</artifactId>
            	<version>0.9.10</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
